# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'AnywhereFitness' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AnywhereFitness
pod 'DropDown'
pod 'SwiftLint'

  target 'AnywhereFitnessTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AnywhereFitnessUITests' do
    # Pods for testing
  end

end
